### ISSUE TITLE
[ADD] What are community Standards to README

### ISSUE THREAD

**Issue by kjaymiller** [Github-Community-Standards/github-community-standards#15] opened 2022-10-28 15:36 UTC
The readme for this page will like be the readme for the project. It would be good to explain what [Github's Community Standards](https://github.com/kjaymiller/github-community-standards/community) are. Sadly, I don't see much in the documentation. So perhaps we get a screenshot when our standards are up to snuff.

**Comment by tnfdesigns** [comment] 2022-10-29 03:31
Duplicate of #6 

hc-I believe this is a duplicate issue because the ["Github Community Standards"](https://github.com/kjaymiller/github-community-standards/community) will live in ./README.md
Before realizing this was a duplicate, I grabbed screenshots of the default(nothing completed except default public repo docs).
Gonna assign this to @jennjunod, she is working on same issue.

-hc

**Closed** 2022-10-31 02:31 UTC
Labels: documentation, hacktoberfest-accepted
